services:
  - type: web
    name: rest-backend
    env: java # Знову env: java
    region: frankfurt
    rootDir: course/
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/course-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: "21"
      - key: SERVER_PORT
        value: "10000"